name: CoLEDS
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - alsa-lib=1.2.13
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - aom=3.6.1
  - appdirs=1.4.4
  - ase=3.23.0
  - astroid=3.3.11
  - async-timeout=5.0.1
  - atk-1.0=2.38.0
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.21.0
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=2.116
  - blas-devel=3.9.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - captum=0.6.0
  - certifi=2025.10.5
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.0
  - click=8.1.8
  - colorama=0.4.6
  - contourpy=1.3.1
  - cryptography=42.0.8
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dataclasses=0.8
  - dbus=1.13.6
  - dill=0.3.8
  - docker-pycreds=0.4.0
  - double-conversion=3.3.0
  - eval_type_backport=0.2.2
  - expat=2.6.4
  - ffmpeg=4.4.2
  - filelock=3.16.1
  - flask=3.1.0
  - flwr=1.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - freetype-py=2.3.0
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.9.0
  - fvcore=0.1.5.post20221221
  - gdk-pixbuf=2.42.12
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - graphql-core=1.1
  - graphviz=12.0.0
  - greenlet=3.1.1
  - gtk2=2.24.33
  - gts=0.7.6
  - h2=4.1.0
  - h5py=3.12.1
  - harfbuzz=9.0.0
  - hdf5=1.14.4
  - hpack=4.0.0
  - huggingface_hub=0.26.5
  - hydra-core=1.3.2
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imageio=2.36.1
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - iopath=0.1.10
  - iperf=3.19.1
  - isodate=0.7.2
  - isort=6.0.1
  - iterators=0.0.2
  - itsdangerous=2.2.0
  - jinja2=3.1.5
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.3
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.6
  - libclang13=19.1.6
  - libcrc32c=1.1.2
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.77
  - libcurl=8.14.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.73.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm19=19.1.6
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.64.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvfatbin=12.6.77
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopengl=1.7.0
  - libparquet=18.1.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.2
  - libprotobuf=6.31.1
  - librdkit=2024.09.3
  - libre2-11=2025.07.22
  - librsvg=2.58.4
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lightning-utilities=0.11.9
  - llvm-openmp=15.0.7
  - llvmlite=0.43.0
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.4.2
  - numba=0.60.0
  - numpy=1.26.4
  - nvidia-ml-py=12.570.86
  - omegaconf=2.3.0
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.4
  - opt_einsum=3.4.0
  - orc=2.1.2
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.54.0
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.44
  - pgmpy=0.1.24
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - portalocker=3.2.0
  - promise=2.3
  - propcache=0.2.1
  - protobuf=6.31.1
  - psutil=6.1.0
  - pthread-stubs=0.4
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycairo=1.27.0
  - pycparser=2.22
  - pycryptodome=3.21.0
  - pydantic=2.10.4
  - pydantic-core=2.27.2
  - pygments=2.18.0
  - pylint=3.3.5
  - pynndescent=0.5.13
  - pyparsing=3.2.0
  - pyside6=6.8.1
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytorch_geometric=2.6.1
  - pytz=2024.1
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.8.1
  - rdflib=7.1.1
  - rdkit=2024.09.3
  - re2=2025.07.22
  - readline=8.2
  - regex=2024.11.6
  - reportlab=4.2.5
  - requests=2.32.3
  - rich=13.9.4
  - rlpycairo=0.2.0
  - s2n=1.5.22
  - safetensors=0.5.3
  - scikit-image=0.25.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - sentry-sdk=2.19.2
  - setproctitle=1.3.4
  - setuptools=75.6.0
  - shellingham=1.5.4
  - six=1.17.0
  - smmap=5.0.0
  - snappy=1.2.1
  - sqlalchemy=2.0.36
  - statsmodels=0.14.4
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tabulate=0.9.0
  - tbb=2021.13.0
  - termcolor=3.1.0
  - threadpoolctl=3.5.0
  - tifffile=2024.12.12
  - tk=8.6.13
  - tokenizers=0.15.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - torchaudio=2.4.1
  - torchmetrics=1.6.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - transformers=4.37.2
  - trimesh=4.5.3
  - typer=0.9.4
  - typing=3.10.0.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wandb=0.21.0
  - wayland=1.23.1
  - wayland-protocols=1.37
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.2
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yacs=0.1.8
  - yaml=0.2.5
  - yarl=1.18.3
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - datasets==3.1.0
      - flwr-datasets==0.5.0
      - grpcio==1.74.0
      - grpcio-tools==1.74.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - msgpack==1.1.0
      - ray==2.10.0
      - referencing==0.35.1
      - rpds-py==0.22.3
      - seaborn==0.13.2
      - slbd==0.2.0
      - thop==0.1.1-2209072238
