apiVersion: v1
kind: Pod
metadata:
  name: boris-HOSTNAME
spec:
  containers:
  - name: fl-client
    image: flserver:5000/slwr/BASEIMAGE:latest
    stdin: true
    tty: true
    command: ["./slurm/measure_cem_runtime.sh"]
    # command: ["/bin/bash"]
    env:
      - name: PYTHONPATH
        value: "."
  imagePullSecrets:
    - name: regcred
  nodeSelector:
    kubernetes.io/hostname: HOSTNAME
